[Queens-only] Restart Erlang VM on undercloud upgrade
When running an undercloud upgrade, yum can upgrade to a newer
major version of Erlang, and it doesn't restart the running
Erlang Port Mapper Daemon (epmd) nor RabbitMQ.

When upgrading from Erlang 18 to Erlang 19, the Erlang VM
implements differently calls to OS commands [1]. This confuses
RabbitMQ recurring monitoring process:

    ERROR: "Free disk space monitor encountered an error (e.g. failed to parse output from OS tools):

and also makes command line tools link management plugin fail
until epmd is restarted:

    $ rabbitmq-plugins list -E -m
    Error: invalid parameter: []

Make sure to restart both epmd and RabbitMQ if they are running,
to start the upgrade from a valid erlang runtime.

We only do that for Queens because starting Rocky, RabbitMQ
is containerized and thus always restart both RabbitMQ and
Erlang VM on container image updates.

[1] https://github.com/erlang/otp/commit/200247f972b012ced0c4b2c6611f091af66ebedd

Change-Id: I6f486b0b70f19d8b4916ef500675c0739939e060
Closes-Bug: #1822120
Co-Authored-By: Peter Lemenkov <plemenko@redhat.com>